stages:        
  - build
  - deploy

build-job:
  stage: build
  image: alpine
  before_script:
    - apk add zip git
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/termalabs/scraper scraper
    - zip -r scraper.zip scraper
  artifacts:
    paths:
      - scraper.zip

deploy-job:      
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no scraper.zip ec2-user@ec2-3-110-121-255.ap-south-1.compute.amazonaws.com:/home/ec2-user/codebase
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-110-121-255.ap-south-1.compute.amazonaws.com "cd /home/ec2-user/codebase;rm -rf scraper/; unzip scraper.zip; rm scraper.zip;cd scraper;pip3 install -r requirements.txt"
