stages:        
  - build
  - deploy

build-dev-job:
  stage: build
  image: alpine
  before_script:
    - apk add zip git
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/termalabs/scraper scraper
    - cd scraper && git checkout dev && git pull origin dev & cd ..
    - zip -r scraper.zip scraper
  artifacts:
    paths:
      - scraper.zip

deploy-dev-job:      
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no scraper.zip ec2-user@ec2-35-154-112-107.ap-south-1.compute.amazonaws.com:/home/ec2-user/codebase
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-154-112-107.ap-south-1.compute.amazonaws.com "cd /home/ec2-user/codebase;rm -rf scraper/; unzip scraper.zip; rm scraper.zip;cd scraper;pip3.8 install -r requirements.txt;cd scrapers; cp config.yml.example config.yml"
